### ISSUE TITLE
Doesn't work after installing thru hpm in hyper 0.8.3

### ISSUE THREAD

**Issue by vors** [abhishekjairath/htyt#3]
Repro
------

On the clean OS X El Capitan installation of hyper 0.8.3

```
> hpm i htyt
```

Then try to use it

```
> htyt."foo"
```

Expected
---------

Search some videos

Actual
------

Command `htyt` not found

**Comment by marclundgren** [comment]
I'm also on hyper `0.8.3`, however instead of seeing `command htyt not found`, I simply see zero output

```
htyt."chocobo mix"
```

**Comment by marclundgren** [comment]
Is there a way to run in verbose/diagnostic mode?

**Comment by abhishekjairath** [comment]
At the moment no. Haven't used hpm, so I will have to see what's happening.

**Comment by hew** [comment]
FWIW I'm getting the behaviour from the OP without using `hpm`

**Comment by cchamberlain** [comment]
+1 just installed fresh hyper with this plugin on Sierra and I get zero output after running the command.

<img width="389" alt="screen shot 2017-01-15 at 1 26 06 pm" src="https://cloud.githubusercontent.com/assets/424694/21966339/3ab97110-db26-11e6-9126-9f3b28a1d128.png">
